// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dca_cal.Data;

#nullable disable

namespace dca_cal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("dca_cal.Data.Crypto", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("value")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Cryptos");
                });

            modelBuilder.Entity("dca_cal.Data.Investment", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CryptoAmount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InvestedAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ROI")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValueToday")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Investments");
                });
#pragma warning restore 612, 618
        }
    }
}
